### ISSUE TITLE
Segmentation Fault 139 (core dumped) occurs when building the code

### ISSUE THREAD

**Issue by HMLONG** [gunrock/mini#1]
When building the code I receive this error:

$make
mkdir -p bin
"/usr/local/cuda-7.5/bin/nvcc" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -std=c++11 -ccbin=/usr/bin/g++-4.8 -Xcompiler="-Wundef" -O2 -g -Xcompiler="-Werror" -lineinfo  --expt-extended-lambda -use_fast_math -Xptxas="-v" -o bin/test_bfs__x86_64 test_bfs.cu -m64 -I.. -I../../src -I"../../../external/moderngpu/src"
Segmentation fault (core dumped)
make: **\* [bin/test_bfs__x86_64] Error 139

My system: 
Ubuntu14.04 64 Bit, 
GeForce GT 740 : 1058.500 Mhz   (Ordinal 0) Compute Capability sm_30 Mem Clock: 2500.000 Mhz x 128 bits   ( 80.0 GB/s)

And I can build gunrock main project successfully. I can not figure out what the problem is.

**Comment by yzhwang** [comment]
Have you checked your gcc version?
http://www.unixguide.net/linux/faq/09.06.shtml
You should use a gcc that supports C++11 feature, say, at least >=4.8
Let me know if updating gcc still couldn't solve the problem.

**Comment by yzhwang** [comment]
@HMLONG Have you been able to solve the problem?

**Comment by HMLONG** [comment]
@yzhwang The Segmentation fault error occured when I used gcc4.8 and g++4.8. I updated compiler to gcc5 and g++5 and then the new error occured:

$make
mkdir -p bin
"/usr/local/cuda-7.5/bin/nvcc" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -std=c++11 -ccbin=/usr/bin/g++-5 -Xcompiler="-Wundef" -O2 -g -Xcompiler="-Werror" -lineinfo  --expt-extended-lambda -use_fast_math -Xptxas="-v" -o bin/test_bfs__x86_64 test_bfs.cu -m64 -I.. -I../../src -I"../../../external/moderngpu/src"
In file included from /usr/local/cuda-7.5/bin/..//include/cuda_runtime.h:76:0,
                 from <command-line>:0:
/usr/local/cuda-7.5/bin/..//include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported
make: **\* [bin/test_bfs__x86_64] Error 1

**Comment by HMLONG** [comment]
The problem occured at morderngpu/transform.hxx line 21:
launch_box_cta_k<launch_box, func_t><<<grid_dim, cta.nt, 0, context.stream()>>>(f, num_ctas, args...);
When I comment this line, the segment fault error gone. I can make successfully but the program can't execute correctlly.

**Comment by HMLONG** [comment]
The problem occured at morderngpu/transform.hxx line 21:
launch_box_cta_k<launch_box, func_t><<<grid_dim, cta.nt, 0, context.stream()>>>(f, num_ctas, args...);
When I comment this line, the segment fault error gone. I can make successfully but the program can't execute correctlly.

**Comment by HMLONG** [comment]
The problem occured at morderngpu/transform.hxx line 21:
`launch_box_cta_k` `<launch_box,` func_t> `<<<grid_dim,``cta.nt, 0, context.stream()>>>(f, num_ctas,`args...);
When I comment this line, the segment fault error gone. I can make successfully but the program can't execute correctlly.

**Comment by yzhwang** [comment]
Yeah... that's a very important line of code :-). So actually I've never tried compiling this in CUDA 7.5 (I've been working on CUDA 8 all the way). Here is my setting:
CUDA 8
gcc/g++ 4.8.5
driver: 367.48

Sorry about this, since this library is only an experimental one, I haven't thoroughly tested it under different hw+sw.
It would also be benefitial if you could try building moderngpu 2.0 first and I assume once you get that done, it won't be difficult to get gunrock mini to build, since other than using moderngpu 2.0, it doesn't have any other dependency. Good luck!

**Comment by HMLONG** [comment]
I updated cuda7.5 to cuda8.0 and then everything goes fine:-). Thanks for lighting up this.
