### ISSUE TITLE
A bug in validation code for mini gunrock PageRank

### ISSUE THREAD

**Issue by YuxinxinChen** [gunrock/mini#4]
The code here:
https://github.com/gunrock/mini/blob/master/gunrock/tests/test_utils.hxx#L208
seem wrong.

It should be 
```
if (fabs(gpu_vals[i] - cpu_vals[i]) > 0.01f) {
      return false;
}
```

**Comment by yzhwang** [comment]
Done in https://github.com/gunrock/mini/commit/5fd1a0eafe161ec91acdbeebca410f62edd82195
